services:
  api:
    build:
      context: ./api/src/PokemonApi
      dockerfile: Dockerfile
    ports:
      - "5189:5189"
    networks:
      - pokemonapp

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - pokemonapp

networks:
  pokemonapp:
